name: Auto Update Playlist

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "#EXTM3U" > playlist.m3u
          while read url; do
            curl -L -s "$url" | grep -v "#EXTM3U" >> playlist.m3u
          done < sources.txt

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add playlist.m3u
          git commit -m "Auto update playlist" || exit 0
          git push
